### ISSUE TITLE
partials still getting cached in development mode

### ISSUE THREAD

**Issue by danieldkim** [dantebronto/picard#11]
this little change to line 224 in request_extensions.js seems to fix it:

http://gist.github.com/462092

**Comment by danieldkim** [comment]
btw, i noticed that the read of the partial template is synchronous.  any reason for that?

**Comment by dantebronto** [comment]
This really bothers me but I can't think of a suitable fix. The partial loading is the only synchronous part of the framework. The reason I had to do this was in the event that someone calls a partial inside of an :each loop. If the partial loading is deferred until later, the partial scope would be lost, that is without majorly refactoring the way views are rendered.
