### ISSUE TITLE
[Request] Param extraction

### ISSUE THREAD

**Issue by aeosynth** [dantebronto/picard#3]
If true is passed as the second argument to require("url").parse, the params in the query string will be extracted. Picard's parsed_url method doesn't let me do this.

**Comment by aeosynth** [comment]
Actually, this isn't that important. url.parse(req.url, true) isn't that much harder to write than req.parsed_url(true).

**Comment by aeosynth** [comment]
To keep everything simple, I went ahead and made query string parsing the default, no on/off option. I mean, who really needs an unparsed query string? And for those that _really_ do, there's always search.substring(1).

**Comment by midnightmonster** [comment]
FWIW, PayPal IPN actually requires access to the unparsed query string. You have to return to them _exactly_ the request they made to you, in the same order. So long as it can be got to some way, though, I don't think there's a problem.
